# Generated by Django 4.2.16 on 2024-10-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0003_book_author_book_is_bestselling"),
    ]

    operations = [
        migrations.AddField(
            model_name="book", name="slug", field=models.SlugField(default=""),
        ),
    ]
