# Generated by Django 4.2.16 on 2024-11-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0007_address_author_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("code", models.CharField(max_length=2)),
            ],
            options={"verbose_name_plural": "Countries",},
        ),
        migrations.AlterModelOptions(
            name="address", options={"verbose_name_plural": "Address Entries"},
        ),
    ]
