# Generated by Django 4.2.16 on 2024-11-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0008_country_alter_address_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="published_countries",
            field=models.ManyToManyField(to="book_outlet.country"),
        ),
    ]
